apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: disktype
                        operator: In
                        values:
                        - ssd
            preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                    preference:
                        matchExpressions:
                        - key: region
                            operator: In
                            values:
                            - us-west
    containers:
    - name: mycontainer
      image: nginx