apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: my-direct-vmi  # Ephemeral VM (deleted if stopped)
spec:
  domain:
    devices:
      disks:
      - name: rootdisk
        disk: {}  # Attaches as a virtio disk
      - name: cloudinitdisk
        disk: {}  # For cloud-init (optional)
    resources:
      requests:
        memory: 2Gi
        cpu: 1
  volumes:
  - name: rootdisk
    containerDisk:
      image: quay.io/containerdisks/fedora:latest  # Ephemeral disk (runs in memory)
  - name: cloudinitdisk
    cloudInitNoCloud:
  userData: |
    #cloud-config
    users:
      - name: fedora
        password: fedora  # Explicitly set
        lock_passwd: false
        sudo: "ALL=(ALL) NOPASSWD:ALL"
    chpasswd: 
      list: |
        fedora:fedora
      expire: false
    runcmd:
      - sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      - systemctl restart sshd
